guesses = ['Gian', 'Melissa', 'Python', 'PHP']
print(guesses)
print(f"-------------------------------------------")
print(f"Hey {guesses[0]} would you like to dinner?")
print(f"Hey {guesses[1]} would you like to dinner?")
print(f"Hey {guesses[2]} would you like to dinner?")
print(f"Hey {guesses[3]} would you like to dinner?")
print(f"-------------------------------------------")
print(f"Guest can't make the dinner: {guesses[3]}")
guesses[3] = 'JavaScript'
print(f"-------------------------------------------")
print(guesses)
print(f"-------------------------------------------")
print(f"Hey {guesses[0]} would you like to dinner?")
print(f"Hey {guesses[1]} would you like to dinner?")
print(f"Hey {guesses[2]} would you like to dinner?")
print(f"Hey {guesses[3]} would you like to dinner?")
print(f"-------------------------------------------")
print(f"A new table has been found")
print(f"-------------------------------------------")
guesses.insert(0, 'React')

print(guesses)
print(f"-------------------------------------------")
guesses.insert(3, 'TailwindCSS')
print(guesses)
print(f"-------------------------------------------")
guesses.append('NextJS')
print(guesses)
print(f"-------------------------------------------")
print(f"Hey {guesses[0]} would you like to dinner?")
print(f"Hey {guesses[1]} would you like to dinner?")
print(f"Hey {guesses[2]} would you like to dinner?")
print(f"Hey {guesses[3]} would you like to dinner?")
print(f"Hey {guesses[4]} would you like to dinner?")
print(f"Hey {guesses[5]} would you like to dinner?")
print(f"Hey {guesses[6]} would you like to dinner?")
print(f"-------------------------------------------")
print(f"Sorry, the invitation it is just for two people")
print(f"-------------------------------------------")
print(f"I'm sorry {guesses.pop(6)}, I can't invite you to the Dinner")
print(f"I'm sorry {guesses.pop(5)}, I can't invite you to the Dinner")
print(f"I'm sorry {guesses.pop(4)}, I can't invite you to the Dinner")
print(f"I'm sorry {guesses.pop(3)}, I can't invite you to the Dinner")
print(f"I'm sorry {guesses.pop(2)}, I can't invite you to the Dinner")
print(guesses)
print(f"-------------------------------------------")
print(f"{guesses[1]}, You're are still invited to the Dinner")
print(f"{guesses[0]}, You're are still invited to the Dinner")
print(f"-------------------------------------------")

del guesses[1]
del guesses[0]
print(guesses)
print(f"-------------------------------------------")
